# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:all)

platform :all do

  desc "Deploy to Firebase App Distribution"
  lane :firebase_distribution do
    gradle(
      task: "assemble",
      build_type: "Release"
    )

    firebase_app_distribution(
      app: "1:969395528079:android:b7219b6300d97039066bfa", # Replace with your Firebase App ID
      groups: "android", # Specify tester groups or emails
      release_notes: "New Android build deployed via Fastlane",
      apk_path: "../build/app/outputs/apk/release/Movie Date-release.apk" # Path to the release APK
    )
  end

  desc "Deploy Debug Build to Firebase App Distribution"
  lane :deploy_debug do
    # gradle(
    #   task: "assemble",
    #   build_type: "Debug"
    # )

    firebase_app_distribution(
      app: "1:969395528079:android:b7219b6300d97039066bfa", # Replace with your Firebase App ID
      groups: "android", # Specify tester groups or emails
      release_notes: "New Android build deployed via Fastlane",
      apk_path: "../build/app/outputs/bundle/release/app-release.aab" # Path to the release APK
    )
  end

  lane :test do
    flutter_version_manager(
      arguments: "-major",
      yml: "/Users/james.preston/Documents/source/flutter/movie_date/version.yml",
      pubspec: "/Users/james.preston/Documents/source/flutter/movie_date/pubspec.yaml")
  end
  
  lane :bump_major do
    flutter_version_manager(
      arguments: "-major",
      yml: "/Users/james.preston/Documents/source/flutter/movie_date/version.yml",
      pubspec: "/Users/james.preston/Documents/source/flutter/movie_date/pubspec.yaml")
  end
  
  lane :bump_minor do
    flutter_version_manager(
      arguments: "-minor",
      yml: "/Users/james.preston/Documents/source/flutter/movie_date/version.yml",
      pubspec: "/Users/james.preston/Documents/source/flutter/movie_date/pubspec.yaml")
  end
  
  lane :bump_patch do
    flutter_version_manager(
      arguments: "-patch",
      yml: "/Users/james.preston/Documents/source/flutter/movie_date/version.yml",
      pubspec: "/Users/james.preston/Documents/source/flutter/movie_date/pubspec.yaml")
  end
  
  lane :read_version do
    flutter_version_manager(
      arguments: "-version",
      yml: "/Users/james.preston/Documents/source/flutter/movie_date/version.yml",
      pubspec: "/Users/james.preston/Documents/source/flutter/movie_date/pubspec.yaml")
  end
  
  lane :read_code do
    flutter_version_manager(
      arguments: "-code",
      yml: "/Users/james.preston/Documents/source/flutter/movie_date/version.yml",
      pubspec: "/Users/james.preston/Documents/source/flutter/movie_date/pubspec.yaml")
  end
  
  lane :apply_new_version do
    flutter_version_manager(
      arguments: "-apply",
      yml: "/Users/james.preston/Documents/source/flutter/movie_date/version.yml",
      pubspec: "/Users/james.preston/Documents/source/flutter/movie_date/pubspec.yaml")
  end
  
  lane :get_help do
    flutter_version_manager(
      arguments: "-h",
      yml: "/Users/james.preston/Documents/source/flutter/movie_date/version.yml",
      pubspec: "/Users/james.preston/Documents/source/flutter/movie_date/pubspec.yaml")
  end

  lane :test_ios do
    Dir.chdir('../ios') { sh("fastlane distribute_ios") }
  end

end

