# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build the iOS app"
  lane :build do
    match(type: "adhoc", app_identifier: "com.dxsolo.movie" ,   readonly: is_ci, git_url: "git@github.com:JamesKPreston/movie_date_match.git")
    build_ios_app(
      scheme: "Runner",
    )
  end
  # desc "Increment the build number"
  # lane :increment_build_number do
  #   latest_release = firebase_app_distribution_get_latest_release(
  #     app: "1:969395528079:ios:120b02032f7882f7066bfa"
  #   )
  #   increment_build_number({ build_number: latest_release[:buildVersion].to_i + 1 })
  # end
  desc "Increment the version"
  lane :increment_version do
    increment_version_number(
      version_number: "1.0.1"
    )
  end 
  desc "Build and Distribute the iOS app"
  lane :distribute_ios do
    increment_version
    build
    firebase_app_distribution(
      app: "1:969395528079:ios:120b02032f7882f7066bfa",
      groups: "dev",
      release_notes: "Infinite Loading Screen Fixed , Invalid Room Code handled ",
    )
  end
end
