# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
setup_ci()
platform :ios do
  desc "Build the iOS app"
  lane :build do
    match(type: "adhoc", app_identifier: "com.dxsolo.movie" ,   readonly: is_ci, git_url: ENV['MATCH_GIT_URL'])
    build_ios_app(
      scheme: "Runner",
    )
  end
  desc "Increment the build number"
  lane :increment_build do
    latest_release = firebase_app_distribution_get_latest_release(
      app: "1:969395528079:ios:120b02032f7882f7066bfa"
    )
    increment_build_number({ build_number: latest_release[:buildVersion].to_i + 1 })
  end
  desc "Increment the version major"
  lane :major do
    increment_version_number(
      bump_type: "major"
    )
  end 

  desc "Increment the version patch"
  lane :patch do
    increment_version_number(
      bump_type: "patch"
    )
  end 

  desc "Increment the version minor"
  lane :minor do
    increment_version_number(
      bump_type: "minor"
    )
  end 
  desc "Build and Distribute the iOS app"
  lane :distribute_ios do
    increment_version
    build
    firebase_app_distribution(
      app: "1:969395528079:ios:120b02032f7882f7066bfa",
      groups: "dev",
      release_notes: "Re-design rooms",
    )
  end

  desc "Build and Distribute the iOS app"
  lane :self do
   
    build
    firebase_app_distribution(
      app: "1:969395528079:ios:120b02032f7882f7066bfa",
      groups: "self",
      release_notes: "Updated to use new go router navigation",
    )
  end

  desc "Build and Distribute the iOS app Spindance"
  lane :deploy_spindance do
    increment_version
    build
    firebase_app_distribution(
      app: "1:969395528079:ios:120b02032f7882f7066bfa",
      groups: "spindance",
      release_notes: "Realtime movie date matching",
    )
  end
end
