# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Deploy to Firebase App Distribution"
  lane :firebase_distribution do
    gradle(
      task: "assemble",
      build_type: "Release"
    )

    firebase_app_distribution(
      app: "1:969395528079:android:b7219b6300d97039066bfa", # Replace with your Firebase App ID
      groups: "android", # Specify tester groups or emails
      release_notes: "New Android build deployed via Fastlane",
      apk_path: "../build/app/outputs/apk/release/Movie Date-release.apk" # Path to the release APK
    )
  end

  desc "Deploy Debug Build to Firebase App Distribution"
  lane :deploy_debug do
    # gradle(
    #   task: "assemble",
    #   build_type: "Debug"
    # )

    firebase_app_distribution(
      app: "1:969395528079:android:b7219b6300d97039066bfa", # Replace with your Firebase App ID
      groups: "android", # Specify tester groups or emails
      release_notes: "New Android build deployed via Fastlane",
      apk_path: "../build/app/outputs/bundle/release/app-release.aab" # Path to the release APK
    )
  end
end

