name: Build and Distribute Android
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Install dependencies
        run: | 
            flutter pub get

      - name: Generate .env file
        run: |
            echo "API_KEY=${{ secrets.API_KEY }}" >> .env
            echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
            echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
          
      # - name: Debug file location
      #   run: ls -la
      # Build the Flutter Android debug APK
      - name: Build Flutter Debug APK
        run: flutter build apk --debug

      # - name: Set up Fastlane
      #   run: |
      #     bundle install
      # - name: Build Android and distribute with Fastlane
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      #   run: |
      #     fastlane deploy_debug