name: Build and Distribute Android
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Build app bundle
        working-directory: ./android
        run: flutter build appbundle --release

      - name: Deploy using Fastlane
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        uses: maierj/fastlane-action@v2.3.0
        with:
          lane: deploy_debug
          subdirectory: android
