name: Build and Distribute iOS
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.4.3'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
      - name: Install dependencies
        run: flutter pub get
      - name: Set up Fastlane
        run: |
          cd ios
          bundle install
      - name: Build iOS and distribute with Fastlane
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          MATCH_GIT_URL: "https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/JamesKPreston/movie_date_match.git"
        run: |
          cd ios
          fastlane distribute_ios